include = ["**/*.toml"]
exclude = ["**/node_modules/**", "**/target/**", "**/.git/**"]

[formatting]
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "workspace.dependencies"]
formatting = { reorder_keys = true }
