[package]
name = "mina-fuzzer"
version = "0.18.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
lazy_static = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
rand_distr = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
