[package]
name = "poseidon"
version = "0.17.0-alpha"
edition = "2021"

[lints]
workspace = true

[dependencies]
ark-ff = { workspace = true }
ark-serialize.workspace = true
mina-curves = { workspace = true }
o1-utils.workspace = true
once_cell = "1"
serde.workspace = true
