[package]
name = "poseidon"
version = "0.16.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
ark-ff = { workspace = true }
ark-serialize.workspace = true
mina-curves = { workspace = true }
once_cell = "1"
serde.workspace = true
