[package]
name = "libp2p-rpc-behaviour"
version = "0.18.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
libp2p = { workspace = true }
log = { workspace = true }
mina-p2p-messages = { workspace = true }
