[package]
name = "libp2p-rpc-behaviour"
version = "0.17.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
libp2p = { workspace = true }
log = { version = "0.4.19" }
mina-p2p-messages = { workspace = true }
