name: Frontend macOS latest

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    runs-on: macos-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - id: versions
        uses: ./.github/actions/load-versions

      - name: Frontend build
        uses: ./.github/actions/frontend-build
        with:
          node-version: ${{ steps.versions.outputs.node-version }}
          test-build-commands: 'true'