name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  lint:
    name: Lint - ${{ matrix.os }} - Rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: [1.84]
    steps:
      - uses: actions/checkout@v4
      - name: Setup build dependencies
        run: |
          sudo apt update || true
          sudo apt install -y protobuf-compiler || true
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt
      - name: Run make check
        run: make check
      - name: Run make lint
        run: make lint

  lint-tx-fuzzing:
    name: Lint transaction Fuzzing - ${{ matrix.os }} - Rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: [nightly]
    steps:
      - uses: actions/checkout@v4
      - name: Setup build dependencies
        run: |
          sudo apt update || true
          sudo apt install -y protobuf-compiler || true
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt
      - name: Run transaction Fuzzing check
        run: make check-tx-fuzzing

  hadolint:
    name: Hadolint - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install hadolint
        run: |
          wget -O /tmp/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /tmp/hadolint
          sudo mv /tmp/hadolint /usr/local/bin/hadolint
      - name: Run hadolint
        run: make lint-dockerfiles
